---

# git user information
git_user: 
git_email: 
git_ssh_key_name: git_rsa

# packages
packages:
  - flatbuffers
  - git
  - xclip
  - keepassxc
  - kubernetes-client
  - libselinux-python
  - libsemanage-python
  - "http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm"
  - "http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm"

# golang
go_path: ~/go
go_repos:
  - github.com/golang/mock/gomock
  - github.com/golang/mock/mockgen
  - github.com/derekparker/delve/cmd/dlv
  - github.com/spf13/cobra/cobra
 
# gnome shortcuts
gnome_shortcuts:
  - {name: terminal, command: gnome-terminal, binding: F4}
