- name: Deploy .inputrc
  copy:
    src: .inputrc
    dest: ~/.inputrc

- name: Deploy .bashrc
  copy:
    src: .bashrc
    dest: ~/.bashrc

- name: Change shell
  become: yes
  command: "chsh -s /usr/bin/bash {{ ansible_user_id }}"