- name: Import keys
  become: yes
  command: rpm --import https://packages.microsoft.com/keys/microsoft.asc

- name: Deploy vscode.repo
  become: yes
  copy:
    src: vscode.repo
    dest: /etc/yum.repos.d/vscode.repo

- name: Install vscode
  become: yes
  dnf:
    name: code
    state: latest

- name: Make sure user settings folder exists
  file:
    path: ~/.config/Code/User/
    state: directory
    recurse: yes
    mode: 0755

- name: Deploy default user settings
  template:
    src: settings.json.j2
    dest: ~/.config/Code/User/settings.json

- name: Deploy key bindings
  copy:
    src: keybindings.json
    dest: ~/.config/Code/User/keybindings.json
